apiVersion: litefunctions.ashupednekar.dev/v1
kind: Function
metadata:
  name: process-order
  namespace: default
spec:
  isActive: true
  isAsync: false
  language: go
  name: processOrder
  method: POST
  project: order-service
  git_creds: github-creds