name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ashupednekar535
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ashupednekar535/slides:latest
            ashupednekar535/slides:${{ github.sha }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ vars.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.ashupednekar }}
          script: |
            docker pull ashupednekar535/slides:latest
            docker restart slides
